#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from source.crop import Crop
from source.resultChecker import verifyResults
import argparse

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--screenshot", action="extend", nargs="+", type=str)
    parser.add_argument("--test", help="Run the test configuration",
                        action="store_true")
    args = parser.parse_args()
    if args.screenshot:
        for screenshot in args.screenshot:
            Crop(screenshot)
    if args.test:
        Crop("./screenshots/screen0.jpg")
        Crop("./screenshots/screen1.png")
        Crop("./screenshots/screen2.png")
        verifyResults()        
